version: "3"
services:
  app:
    build:
      args:
        user: kim
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: listing
    container_name: listing-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - listing

  db:
    image: mysql:5.7
    container_name: listing-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - listing

  nginx:
    image: nginx:alpine
    container_name: listing-nginx
    restart: unless-stopped
    ports:
      - 6000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - listing

networks:
  listing:
    driver: bridge
